version: '3.3'
services:
  # Used primarily for the sake of running dynamic configurations
  php_fpm:
    build:
      context: .
    volumes:
      - ./fpm.conf:/etc/php/7.2/fpm/php-fpm.conf
      - ./php.ini:/etc/php/7.2/fpm/php.ini
      - ./pool.conf:/etc/php/7.2/fpm/pool.d/www.conf
